### ISSUE TITLE
Compile warning about address of local temporary object

### ISSUE THREAD

**Issue by bwspenc** [Argonne-National-Laboratory/neml#105]
Compiling BlackBear (which includes NEML) in debug mode shows this warning that indicates a potentially serious issue:

```
/Users/reverendbedford/projects/blackbear/contrib/neml/src/objects.h:121:12: warning: returning address of local temporary object [-Wreturn-stack-address]
    return ss.str().c_str();
           ^~~~~~~~
```

(User name swapped :smile:)

**Comment by reverendbedford** [comment]
Thanks.  This is already fixed on the current dev (see [here](https://github.com/Argonne-National-Laboratory/neml/commit/9c272372dd280d6f828ec9c20a5db71b81c156b7)).

**Comment by bwspenc** [comment]
Oh, good -- thanks!  I'll just update our submodule version and this should go away. I didn't look into this at all myself -- just passed this on from someone else who saw it.
