### ISSUE TITLE
NEML OpenBLAS issue and util for Ansys

### ISSUE THREAD

**Issue by balamurata123** [Argonne-National-Laboratory/neml#107]
Hello, 
Tried building neml on Win10 machine with installed LAPACK and BLAS through OpenBlas, but `cmake` invoke gives me an error that it is unable to find BLAS. Has anybody experienced similar issue ?: 

```
D:\GITlib\neml>cmake -DCMAKE_CXX_COMPILER=icl.exe -DBLA_VENDOR=OpenBLAS -DBoost_INCLUDE_DIR="D:\GITlib\boost" -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=False -G Ninja .
CMake Error at D:/GITlib/cmake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  D:/GITlib/cmake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  D:/GITlib/cmake/share/cmake-3.20/Modules/FindBLAS.cmake:1045 (find_package_handle_standard_args)
  CMakeLists.txt:42 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "D:/GITlib/neml/CMakeFiles/CMakeOutput.log".
See also "D:/GITlib/neml/CMakeFiles/CMakeError.log".
```

A second point - neml looks like a great suite of models, but it appears the community can only use \util for Abaqus. Is there an equivalent for ANSYS? Thx

**Comment by reverendbedford** [comment]
I haven't run into this in particular, but you can try setting 

`-DBLAS_blas_LIBRARY=C:/path/to/actual/blas/lib.dll -DLAPACK_lapack_LIBRARY=C:/path/to/actual/lapack/dll`

to hardwire it to the correct library.

We don't have and official ANSYS UMATERIAL yet, but there is a user here at ANL that uses NEML with ANSYS.  I believe the process is fairly similar to ABAQUS.  I'll see if he has more specific guidance.

**Comment by balamurata123** [comment]
Thanks for the useful suggestions, that should do it for BLAS!
