### ISSUE TITLE
min compiler version?

### ISSUE THREAD

**Issue by hugary1995** [Argonne-National-Laboratory/neml#134]
This is weird: I can configure cmake and compile just fine without the python binding. But if I set `WRAP_PYTHON=ON` I get the following error:
```
CMake Error in src/CMakeLists.txt:
  The compiler feature "cxx_inheriting_constructors" is not known to CXX
  compiler

  "GNU"

  version 9.3.1.
```

However, even after the error, cmake is able to write build files, and it seems that neml compiles fine.

**Comment by reverendbedford** [comment]
I have 9.3.1 installed and I can't reproduce this with a clean clone of `dev` by running 

`cmake -DWRAP_PYTHON=ON .`

Random googling suggests that you shouldn't seed this with gcc 4.8+.  Are you sure that cmake pulled gcc 9.3.1 as the compiler and not the default installed version on centos?  You can can check with (after configuring)

`cmake -LA . | grep CMAKE_CXX_COMPILER`

Separate issue, but I should be calling out some minimum gcc version in the `CMakeLists.txt`.  I need to try out a few versions to see which ones work, probably do that at home on a Docker or something and make a PR.

**Comment by hugary1995** [comment]
I can't reproduce it either :smiling_face_with_tear:
