### ISSUE TITLE
NEMLScalarDamagedModel_sd::get_damage returns wrong answer

### ISSUE THREAD

**Issue by maxnezdyur** [Argonne-National-Laboratory/neml#163]
@reverendbedford @hugary1995 
I am using NEML within MOOSE, and I am trying to output the damage index for visualization.
`NEMLScalarDamagedModel_sd::get_damage` is returning the wrong answer. Its seems to be returning the the value at the wrong index. 
I'll try to explain as much as I can, using debugging outputs that I have.  The problem I am running should have damage everywhere within the first time step. 
The history as a quadrature point is below. Given that I know there is damage and that the damage should be between 0 and 1, I assume that the last value is the correct value. 
```
_hist[_qp]
size=8
[0]: 0
[1]: 0
[2]: 0
[3]: 0
[4]: 0
[5]: 0
[6]: 10.025091709671862
[7]: 0.47206766361193314

```
Looking in ` NEMLScalarDamagedModel_sd::get_damage(const double *const h_np1) ` 
```
History h = gather_history_(h_np1);
return h.get<double>(prefix("damage"));
```
we can see that the actual return value will be the 6th index which would give an answer of 10.
```
h.loc_
size=3
[0]: {first:"small_stress", second:0}
[1]: {first:"damage", second:6}
[2]: {first:"alpha", second:7}
```

The XML file is below, I only added the `<alpha> 0.99 </alpha>` parameter for a hunch that `alpha` is never outputted into history but messes up the indexing, but I don't know if its supposed to actually be placed into history anyway. Let me if you need more information. 
```
<materials>
  <test_powerdamage type="NEMLScalarDamagedModel_sd">
       <dkill> 0.25</dkill>
       <alpha> 0.99 </alpha>
    <elastic type="IsotropicLinearElasticModel">
      <m1>92000.0</m1>
      <m1_type>youngs</m1_type>
      <m2>0.3</m2>
      <m2_type>poissons</m2_type>
    </elastic>

    <base type="SmallStrainRateIndependentPlasticity">
      <elastic type="IsotropicLinearElasticModel">
        <m1>92000.0</m1>
        <m1_type>youngs</m1_type>
        <m2>0.3</m2>
        <m2_type>poissons</m2_type>
      </elastic>
      <flow type="RateIndependentAssociativeFlow">
        <surface type="IsoJ2"/>
        <hardening type="LinearIsotropicHardeningRule">
          <s0>180.0</s0>
          <K>1000.0</K>
        </hardening>
      </flow>
    </base>

    <damage type="PowerLawDamage">
      <elastic type="IsotropicLinearElasticModel">
        <m1>92000.0</m1>
        <m1_type>youngs</m1_type>
        <m2>0.3</m2>
        <m2_type>poissons</m2_type>
      </elastic>
      <A>2.0e-5</A>
      <a>2.2</a>
    </damage>

  </test_powerdamage>

</materials>
```

**Comment by reverendbedford** [comment]
So in that model h[6] should be damage...  h[7] is the equivalent plastic strain.

Do you get reasonable answers at small values of load?  If you don't have element deletion on there is nothing to stop NEML damage models from assuming "stupid" values of damage -- it just continues to integrate the equations until they explode.

**Comment by maxnezdyur** [comment]
Yes, with small values of load I do get answers below 1,  I am creating a BlackBear test, so to get the model fully damaged I use large load steps and can't really say if they are reasonable because I am not comparing them to anything specific . Thanks for the help, I don't think there is any problem!
