### ISSUE TITLE
Fix out of bounds access

### ISSUE THREAD

**Issue by bwspenc** [Argonne-National-Laboratory/neml#22]
We were trying to add a couple of simple regression tests that compare against native MOOSE models for linear strain hardening plasticity and power law creep in this BlackBear PR: 
https://github.com/idaholab/blackbear/pull/65
The power law creep model encounters an out-of-bounds access error on line 1088 of models.cxx when run with the debug options that we use because it's trying to access index 0 of a history variable array that happens to be of size 0 in our case because we're using a perfect plasticity model.

I think the right fix here is to check for that case and pass in a null pointer to the function that needs the history data.  I'll submit a PR with a proposed fix.

**Comment by reverendbedford** [comment]
Closed by #23
