### ISSUE TITLE
Remove Boost dependency

### ISSUE THREAD

**Issue by bwspenc** [Argonne-National-Laboratory/neml#64]
NEML (at least the parts I use, not the wrappers) depends on the Boost library because of its use of `variant`.  Although we (MOOSE) support pulling in the full Boost library, it's a non-standard way of building the code, and has been causing an unreal amount of headaches with our testing system because of unintended side effects.

To give an example, we were getting inundated with compiler warning messages coming from another boost file we were including (unrelated to `variant`), which actually made our builds fail because the system couldn't handle the sheer volume of output.

At a minimum, NEML's dependency on boost is a barrier to its more widespread use because using it requires recompiling libmesh with boost, which is nonstandard and enough of a pain to do that someone has to be serious about using those models to go to that trouble.

Anyway, suffice it to say that I think that the small benefit obtained from using `variant` doesn't justify the pain of building with boost. I see that `variant` is supported in C++17, which we are talking about moving to, so that could solve that problem, but we're a little ways off from being there. I would propose that NEML use a design more like what we use in libmesh/MOOSE, where we have templated classes that store parameters of various types. It looks to me like the effects of that change would be pretty localized to a small part of the NEML codebase.

Since I'm asking for this, I'm happy to implement it. If you guys absolutely hate what I come up with, maybe you can move back to using `variant` in a while when everyone is using C++17.

**Comment by reverendbedford** [comment]
I agree this should be done and you're right we only use boost for the variant class.  I'm not particularly attached to it, it just seemed to be the most straightforward solution at the time.

If you can get a basic PR that passes all the current tests I'll look at it in detail, work on the error handling (which is bad right now), and merge it in.

**Comment by bwspenc** [comment]
I haven't started on any code, and it might be a little bit until I get to this, but good to know you're on board with the idea. It looks like `boost::variant` does what you want with probably the least amount of code, but hopefully another solution won't require too much more.
