### ISSUE TITLE
Add assertions

### ISSUE THREAD

**Issue by dschwen** [Argonne-National-Laboratory/neml#78]
I'm having some difficulties debugging NEML runs where I run into floating point exceptions. The problem here is that the actual FPE comes fairly late in the game (eigenvalue decomposition), after previous calculations returned `Inf` several steps before in a separate branch of the call tree (that is not in the backtrace). 

In my particular case the first accident is occurring in the hardening rule:

```
int VoceIsotropicHardeningRule::q(const double * const alpha,
                                    double T, double * const qv) const
{
  qv[0] = -s0_->value(T) - R_->value(T) * (1.0 - exp(-d_->value(T) * alpha[0]));
 ...
```

Where `qv[0]` ends up being `Inf` because `alpha[0] < -1000.0` and `d_->value(T) ~ 1`.

I suggest adding a bunch of assertions... and maybe a few more comments in the code to explain teh physical meaning of each calculated quantity...

**Comment by reverendbedford** [comment]
#2 would fix this (in progress now).
