### ISSUE TITLE
Floating Point Exception

### ISSUE THREAD

**Issue by dschwen** [Argonne-National-Laboratory/neml#89]
In certain models the value for `yv` [in general_flow.cxx:81](https://github.com/Argonne-National-Laboratory/neml/blob/1da919389faf22e39daf0c33e62ef14983e087be/src/general_flow.cxx#L81) can get very large. This will cause a LAPACK call in line 103 to throw a floating point exception. 

In MOOSE this hardware exception will be caught by libMesh and result in the termination of the simulation. What we actually want is soft abort the current step and retry with a smaller time step. If I insert a line 83

```
  if (yv > 1e10) return LINALG_FAILURE;
```

This works beautifully. I picked `1e10` randomly (`1e50` still led to the FPE), which is not quite satisfactory. If you have more physical insight you may have a better rationale for a threshold value.

**Comment by dschwen** [comment]
More precisely `yv` can easily become `Inf` for time steps chosen too large.

**Comment by reverendbedford** [comment]
That's the scalar part of the inelastic strain rate, so it's analogous to the A*\sigma^n term in a scalar viscoplastic model.  So yes, it can get big for large values of stress.

Overflow to inf is probably actually the right behavior, I'm surprised that the dgemv call doesn't handle that nicely.  Or do you guys have feenableexcept set in MOOSE?

I guess I have no objections to returning an error though.  The only annoyance is that yv here has units of stress so a reasonable cutoff may depend on the unit system the user is applying.  But honestly I'm not too worried about that.

I'll think about it overnight and then just do something hacky when I inevitably can't find a better solution.  Maybe I'll just provide a `#define STRESS_MAX` somewhere and use that.

I'll put in a PR tomorrow and have one of the ANL people review it.  I'll ping you so you can make sure it resolves your issue and should have it merged to dev tomorrow.

**Comment by dschwen** [comment]
In the meantime I'm working on setting up a custom SIGFPE handler that will
trap this error. This is a bit of a gray area and might not be super
portable code....

**Comment by dschwen** [comment]
Actually, I could really use the scalar part of the inelastic strain rate in MOOSE to inform timestepping. We do have an FPE handler that dumps a backtrace. Ignoring the FPE would not really help, as the end result of the calculation would be garbage (or at least not useful for FEM purposes, right?). And by the time to execution flow is back in MOOSE I'd have to inspect all stress tensor (and tangent operator?) components to see if they are irregular.

**Comment by dschwen** [comment]
Rather than a compile time define you could make this a configurable and optional threshold. Default it to 0 and in that case make no check, or let the main application (i.e. blackbear) set it to some value. 

"Some value" would basically just determine the maximum timestep that could be taken. In the worst case, with the wron assumption for the units, that step would be too small. 

We should be guarding against time steps that are too big anyways, to avoid time integration error. And my intuition is that time integration error becomes a problem _long_ before FPEs or non-convergence of the internal Newton solve becomes an issue.

**Comment by dschwen** [comment]
You could make `yv` a member of the general flow rule and could add a getter in model to retrieve it (using virtual functions to return 0 - or an applicable analog - for rate independent flow rules).

That way I could do the threshold checking completely outside of NEML  **and** I could use that value for time step limiting!

Currently I'm computing the L2 norm of the difference in inelastic strain tensors, which is rather costly (compared to using the value you compute anyways).

**Comment by arovinelli** [comment]
> In certain models the value for `yv` [in general_flow.cxx:81](https://github.com/Argonne-National-Laboratory/neml/blob/1da919389faf22e39daf0c33e62ef14983e087be/src/general_flow.cxx#L81) can get very large. This will cause a LAPACK call in line 103 to throw a floating point exception.
> 
> In MOOSE this hardware exception will be caught by libMesh and result in the termination of the simulation. What we actually want is soft abort the current step and retry with a smaller time step. If I insert a line 83
> 
> ```
>   if (yv > 1e10) return LINALG_FAILURE;
> ```
> 
> This works beautifully. I picked `1e10` randomly (`1e50` still led to the FPE), which is not quite satisfactory. If you have more physical insight you may have a better rationale for a threshold value.

@dschwen why you don't try to use std::infinite(), I would fill much more conformable with it rather than setting some arbitrary threshold

**Comment by dschwen** [comment]
See above, the LAPACK routine already fails for values a lost smaller than infinity (:-D). 1e50 is too large for example.

**Comment by dschwen** [comment]
It might be possible to make the comparison unit independent. We'd have to inspect `sdot` and `erate` when they are passed into `mat_vec`. The FPE will depend on the magnitude of those arguments regardless of units.

**Comment by arovinelli** [comment]
Why don't we catch the dgemv exception in nemlmath?
this way is something goes wrong we can return a non zero value that will trigger a soft failure.

**Comment by dschwen** [comment]
It is not a C++ exception, it is a POSIX signal!

**Comment by reverendbedford** [comment]
Ya, I don't think we want to try to handle the feenableexcept stuff.

I'm okay with making it a configurable option during compile.  We could use it elsewhere to help our non-MOOSE use cases too.  Right now with the python drivers the inf overflow feeds into the newton-raphson loop, which then runs miter iterations and (obviously) doesn't converge.  At that point adaptive stepping takes over and the python drivers subdivide the step.  But you still waste all those pointless iterations before it catches on.

I have a call but I'll put in a PR after lunch.

**Comment by reverendbedford** [comment]
@dschwen sorry for the delay, can you try the stress_limit branch over on PR #90

**Comment by reverendbedford** [comment]
Closed with PR #90
