### ISSUE TITLE
NEML should provide line number when the xml has a mistake

### ISSUE THREAD

**Issue by arovinelli** [Argonne-National-Laboratory/neml#97]
The following file has a typo on line 9.
    `<plastic type = type="GeneralIntegrator">`
[GR91CPfit.txt](https://github.com/Argonne-National-Laboratory/neml/files/6224881/GR91CPfit.txt)

The parser errors out but it does not provide a line number, which it should.
Andrea

**Comment by reverendbedford** [comment]
Unfortunately I forgot that rapidxml doesn't provide line numbers...  I miss libxml.
